### ISSUE TITLE
minimum supported IRIS version is 2022.2

### ISSUE THREAD

**Issue by cmourzelas** [ItzosNL/Intersystems-Monitoring-Elastic#1]
Hello,

It is not an issue but a solution.

For 2022.2 support, juste change that in class IRISELK.BussinessOperation.Config.cls :

/// Load config from file
ClassMethod Load(Output sc As %Status) As %DynamicObject
{

            **//set json = {}.%FromJSONFile(^AAISMonitoringConfig)**
            set stream = ##class(%Stream.FileCharacter).%New()
            set sc = stream.LinkToFile(^AAISMonitoringConfig)
            set json = ##class(%DynamicAbstractObject).%FromJSON(stream)

**Comment by isc-tstolker** [comment]
Thanks, Claude, This has been fixed in version 1.0.20 as released yesterday
